version: "3.8"
services:
  ss-server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    environment:
      - METHOD=aes-256-cfb
      - PASSWORD_SECRET=ss_password_secret
    restart: always

secrets:
  ss_password_secret: